package model.cards;

public enum CardType {
    BANG, MISSED, GATLING, INDIANS, BEER, SALOON, STAGECOACH, PANIC,
    CAT_BALOU, DUEL, GENERAL_STORE, WELLS_FARGO,
    JAIL, BARREL, DYNAMITE, MUSTANG,  SCOPE,
    VOLCANIC, SCHOFIELD, REMINGTON, CARABINE, WINCHESTER, COVER;
}
